"""70天大模型应用开发培训课程 — 每日课纲数据定义"""

COURSE_META = {
    "title": "零基础大模型应用开发 70 天培训课程",
    "total_days": 70,
    "hours_per_day": "6-8",
    "stack": "Python、LangChain、LlamaIndex、OpenAI/DeepSeek/Qwen API、FastAPI、向量数据库、Docker",
}

PHASES = [
    {"id": 1, "name": "Python 编程基础", "days": (1, 14)},
    {"id": 2, "name": "大模型基础理论与 Prompt 工程", "days": (15, 24)},
    {"id": 3, "name": "LangChain 与 RAG 开发", "days": (25, 38)},
    {"id": 4, "name": "Agent 智能体开发", "days": (39, 50)},
    {"id": 5, "name": "模型微调与部署", "days": (51, 60)},
    {"id": 6, "name": "毕业设计与就业冲刺", "days": (61, 70)},
]

# 每日课纲：(标题, 上午主题列表, 下午主题列表, 晚自习主题列表, 实操项目, 核心技能点, 与前后衔接说明)
DAYS = {
    1: (
        "开发环境与第一行代码",
        [
            "课程介绍、大模型行业全景与职业路径分析",
            "安装 Python 3.10+、VS Code、配置国内镜像源",
            "变量、数据类型(int/float/str/bool)、print 与 input",
        ],
        ["编写「个人信息卡片」程序"],
        ["配置 Git 与 GitHub 账号，学会提交代码"],
        "个人信息卡片程序",
        ["Python 环境搭建", "变量与基本类型", "print/input", "Git 初识"],
        "课程起点。为 Day 2 字符串处理与 Day 12 API 调用打基础。",
    ),
    2: (
        "运算符与字符串",
        [
            "算术/比较/逻辑运算符、运算优先级",
            "字符串索引、切片、常用方法(split/join/strip/replace/format)",
            "f-string 格式化（后续写 Prompt 模板的核心技能）",
        ],
        ["文本清洗小工具（去空格、统一大小写、敏感词替换）"],
        ["复习 Day 1 代码，完成字符串练习题"],
        "文本清洗小工具",
        ["运算符", "字符串操作", "f-string"],
        "承接 Day 1 变量基础，为 Day 17 Prompt 模板中的 f-string 埋伏笔。",
    ),
    3: (
        "流程控制",
        [
            "if/elif/else 条件判断、嵌套条件",
            "while 循环、for 循环、range、break/continue",
        ],
        ["猜数字游戏", "九九乘法表", "简易菜单系统"],
        ["LeetCode 简单题 2 道"],
        "猜数字游戏 + 简易菜单系统",
        ["条件分支", "循环", "用户交互菜单"],
        "承接 Day 2 字符串，为 Day 14 多轮对话助手的指令解析(/clear 等)做准备。",
    ),
    4: (
        "核心数据结构（上）",
        [
            "列表 list 的增删改查、切片、排序、列表推导式",
            "元组 tuple、集合 set 的应用场景",
        ],
        ["待办事项管理器（纯命令行版）"],
        ["扩展待办事项：支持优先级排序"],
        "命令行待办事项管理器",
        ["list", "tuple", "set", "列表推导式"],
        "承接 Day 3 循环，messages 列表将在 Day 12/14 用于多轮对话。",
    ),
    5: (
        "核心数据结构（下）—— 字典重点日",
        [
            "字典 dict 的增删改查、嵌套字典、遍历",
            "JSON 格式详解（与 API 交互的基石，重点！）",
            "json 模块的 loads/dumps/load/dump",
        ],
        ["解析一份模拟的 API 返回 JSON，提取指定字段"],
        ["手写 3 个嵌套 JSON 并用代码遍历"],
        "API JSON 解析练习",
        ["dict", "JSON", "json 模块"],
        "承接 Day 4 列表，JSON 是 Day 12 调用大模型 API 的必备技能。",
    ),
    6: (
        "函数",
        [
            "函数定义、参数(位置/关键字/默认值/*args/**kwargs)、返回值",
            "作用域、匿名函数 lambda、递归入门",
        ],
        ["把前几天的小项目重构为函数式结构"],
        ["为文本清洗工具添加单元测试式自测函数"],
        "项目函数化重构",
        ["函数", "lambda", "作用域"],
        "承接 Day 1-5 小项目，为 Day 10 模块化拆分做铺垫。",
    ),
    7: (
        "第一周复习与周测",
        [
            "知识点串讲、答疑",
            "周测（笔试 + 上机）",
        ],
        ["命令行版「通讯录管理系统」（增删改查 + JSON 持久化）"],
        ["整理本周 Git 提交记录，写学习笔记"],
        "通讯录管理系统",
        ["第一周综合", "JSON 持久化", "CRUD"],
        "第一周收官。为 Day 8 OOP 和 Day 14 项目一做能力验收。",
    ),
    8: (
        "面向对象编程（上）",
        [
            "类与对象、属性与方法、__init__ 构造方法",
            "实例方法、类方法、静态方法",
        ],
        ["定义 ChatMessage 类(role、content 属性)——为后面对话应用做铺垫"],
        ["扩展 ChatMessage：添加 to_dict / from_dict"],
        "ChatMessage 类",
        ["class", "__init__", "方法类型"],
        "承接 Day 5 JSON，ChatMessage 将在 Day 14/25 对话系统中复用。",
    ),
    9: (
        "面向对象编程（下）",
        [
            "继承、多态、方法重写、super()",
            "魔术方法(__str__、__repr__、__call__)、属性装饰器 @property",
        ],
        ["设计 BaseModel → OpenAIModel / QwenModel 的类继承结构"],
        ["为模型类添加统一 chat() 接口"],
        "多模型类继承结构",
        ["继承", "多态", "魔术方法"],
        "承接 Day 8，为 Day 25 LangChain ChatModel 统一接口做概念铺垫。",
    ),
    10: (
        "模块、包与异常处理",
        [
            "import 机制、创建自己的模块和包、if __name__ == '__main__'",
            "try/except/else/finally、自定义异常、raise",
            "虚拟环境 venv / conda、pip 与 requirements.txt",
        ],
        ["把项目拆分为多文件包结构"],
        ["编写 requirements.txt 并在新 venv 中复现环境"],
        "多文件包结构项目",
        ["模块", "异常处理", "venv"],
        "承接 Day 6 函数化，为 Day 14 企业级项目目录规范做准备。",
    ),
    11: (
        "文件操作与常用标准库",
        [
            "文件读写(txt/csv/json)、with 上下文管理器、编码问题(UTF-8)",
            "os、pathlib、datetime、random、re 正则表达式入门",
        ],
        ["批量文档读取与关键词统计工具（RAG 文档处理的前置技能）"],
        ["用正则清洗一份脏文本数据"],
        "文档关键词统计工具",
        ["文件 IO", "pathlib", "re 正则"],
        "承接 Day 5 JSON，为 Day 28 文档加载与 Day 30 RAG 铺路。",
    ),
    12: (
        "网络请求与 API 调用（关键日！）",
        [
            "HTTP 协议基础(GET/POST、状态码、Header、Body)",
            "requests 库详解",
            "首次调用大模型 API（DeepSeek 或通义千问免费额度）",
            "理解 API Key、请求体结构、messages 格式、解析返回结果",
        ],
        ["写一个命令行 AI 问答小程序"],
        ["阅读 API 文档，整理请求/响应字段表"],
        "命令行 AI 问答小程序",
        ["HTTP", "requests", "大模型 API", "messages"],
        "承接 Day 5 JSON + Day 8 ChatMessage，正式进入大模型开发主线。",
    ),
    13: (
        "进阶语法与异步入门",
        [
            "装饰器原理与应用、生成器与 yield",
            "类型注解 typing、asyncio 异步编程入门(理解 async/await)",
            "环境变量管理(python-dotenv，保护 API Key)",
        ],
        ["给 API 调用加上重试装饰器与超时控制"],
        ["用 dotenv 管理多环境 API Key"],
        "带重试与超时的 API 客户端",
        ["装饰器", "asyncio", "dotenv"],
        "承接 Day 12 API 调用，为 Day 23 FastAPI 异步接口埋伏笔。",
    ),
    14: (
        "阶段考核 —— 项目一：命令行多轮对话 AI 助手",
        [
            "项目需求讲解与架构设计",
            "多轮对话记忆(messages 列表)实现",
        ],
        [
            "对话历史保存为 JSON",
            "异常处理、支持指令(/clear、/save、/exit)",
            "代码互评 + 讲师点评",
        ],
        ["优化项目 README 并推送 GitHub"],
        "命令行多轮对话 AI 助手",
        ["多轮对话", "JSON 持久化", "指令系统", "异常处理"],
        "第一阶段收官项目。能力将贯穿 Day 15-24 Prompt 与 Web 开发。",
    ),
    15: (
        "大模型原理科普（无需数学基础）",
        [
            "NLP 发展简史：从规则到统计到神经网络到 Transformer",
            "通俗理解 Transformer：注意力机制是什么（类比讲解）",
            "预训练、SFT、RLHF 三阶段；Token 是什么、分词器演示",
            "主流模型盘点：GPT 系列、Claude、DeepSeek、Qwen、Llama、GLM",
        ],
        ["用 tiktoken 计算 token 数，估算 API 成本"],
        ["对比不同模型的 token 单价表"],
        "Token 成本估算实验",
        ["Transformer 科普", "Token", "模型生态"],
        "第二阶段起点。承接 Day 12 API，为 Day 16 参数调优奠基。",
    ),
    16: (
        "大模型 API 核心参数详解",
        [
            "temperature、top_p、max_tokens、frequency_penalty 逐一实验对比",
            "system / user / assistant 角色详解",
            "流式输出 stream=True 的实现（打字机效果）",
        ],
        ["做一个参数对比实验报告（同一 Prompt 不同参数的输出差异）"],
        ["实现流式输出的命令行打印效果"],
        "API 参数对比实验",
        ["temperature", "流式输出", "角色消息"],
        "承接 Day 15 Token，为 Day 17 Prompt 工程提供调参基础。",
    ),
    17: (
        "Prompt 工程基础",
        [
            "Prompt 设计四要素：指令、上下文、输入、输出格式",
            "Zero-shot / Few-shot / One-shot 提示",
            "角色扮演法、分隔符使用、输出格式约束（要求输出 JSON）",
        ],
        ["编写 10 个不同场景的 Prompt 并迭代优化（翻译、摘要、改写、分类）"],
        ["整理个人 Prompt 模板库 v1"],
        "10 场景 Prompt 优化",
        ["Prompt 四要素", "Few-shot", "JSON 输出约束"],
        "承接 Day 2 f-string 与 Day 16 角色消息，Prompt 能力贯穿全课程。",
    ),
    18: (
        "Prompt 工程进阶",
        [
            "思维链 CoT(Chain of Thought)、'let's think step by step'",
            "自洽性(Self-Consistency)、思维树 ToT 概念",
            "Prompt 攻击与防御（提示词注入、越狱）、防注入实践",
            "结构化输出：JSON Mode、Function Calling 初探",
        ],
        ["构建一个「智能客服意图分类器」（输出结构化 JSON）"],
        ["测试 3 种 Prompt 注入攻击并加固"],
        "智能客服意图分类器",
        ["CoT", "Prompt 注入防御", "JSON Mode"],
        "承接 Day 17 基础 Prompt，为 Day 19 Function Calling 做准备。",
    ),
    19: (
        "Function Calling / Tool Use（重点日！）",
        [
            "Function Calling 原理与完整流程图解",
            "定义工具 Schema、模型返回工具调用、执行并回传结果",
            "多工具场景：天气查询 + 计算器 + 数据库查询",
        ],
        ["手写一个能查天气、算数学题的 AI 助手（不用框架，纯 API）"],
        ["绘制 Function Calling 时序图"],
        "多工具 AI 助手（纯 API）",
        ["Function Calling", "Tool Schema", "工具编排"],
        "承接 Day 18 结构化输出，为 Day 40/41 Agent 开发奠基。",
    ),
    20: (
        "多模态与嵌入模型",
        [
            "多模态模型 API 使用（图片理解、图片生成 DALL-E / 通义万相）",
            "Embedding 嵌入模型详解：文本向量化、余弦相似度计算",
            "动手计算句子相似度，理解语义检索的原理（RAG 的核心前置知识）",
        ],
        ["用 Embedding 实现一个「相似问题匹配」小工具"],
        ["可视化 2D 词向量散点图（可选降维）"],
        "相似问题匹配工具",
        ["Embedding", "余弦相似度", "语义检索"],
        "承接 Day 19 工具调用，Embedding 是 Day 29-30 RAG 的核心。",
    ),
    21: (
        "周测 + 综合练习",
        [
            "周测（Prompt 工程 + API 使用）",
        ],
        ["多轮对话 + 工具调用 + 流式输出的整合小项目"],
        ["复盘第二/三周知识图谱"],
        "整合小项目（对话+工具+流式）",
        ["Prompt", "API", "工具调用", "流式"],
        "第二/三阶段过渡。为 Day 22-24 Web 开发做准备。",
    ),
    22: (
        "前端速成",
        [
            "HTML/CSS 快速入门（只学够用的）",
            "JavaScript 基础、fetch 请求",
        ],
        ["写一个静态聊天界面页面"],
        ["美化聊天界面，添加暗色模式"],
        "静态聊天界面",
        ["HTML", "CSS", "JS fetch"],
        "承接 Day 16 流式概念，为 Day 24 前后端联调做准备。",
    ),
    23: (
        "FastAPI 后端开发（上）",
        [
            "FastAPI 入门：路由、路径参数、查询参数、自动文档",
            "Pydantic 数据模型、请求体校验、响应模型",
        ],
        ["把 AI 对话功能封装成 REST API"],
        ["阅读 FastAPI 自动生成的 Swagger 文档"],
        "AI 对话 REST API",
        ["FastAPI", "Pydantic", "REST"],
        "承接 Day 13 异步与 Day 14 对话逻辑，为 Day 24 SSE 流式接口铺垫。",
    ),
    24: (
        "FastAPI 后端开发（下）+ 数据库",
        [
            "SSE 流式接口（对接大模型流式输出）、CORS 跨域",
            "SQLite + SQLAlchemy 基础（保存对话历史到数据库）",
        ],
        ["前后端联调：网页版 ChatGPT 克隆（带流式打字机效果）"],
        ["部署到本地并录制演示 GIF"],
        "网页版 ChatGPT 克隆",
        ["SSE", "CORS", "SQLAlchemy"],
        "第二阶段收官。Web 能力将用于 Day 36-37 知识库项目和毕业设计。",
    ),
    25: (
        "LangChain 入门",
        [
            "LangChain 架构总览、为什么需要框架、生态介绍(LangChain/LangGraph/LangSmith)",
            "ChatModel 接口、统一调用不同厂商模型、PromptTemplate / ChatPromptTemplate",
        ],
        ["用 LangChain 重写之前的对话应用"],
        ["对比纯 API 版与 LangChain 版代码量"],
        "LangChain 对话应用",
        ["LangChain", "ChatModel", "PromptTemplate"],
        "第三阶段起点。承接 Day 9 多模型类和 Day 14 对话项目。",
    ),
    26: (
        "LCEL 表达式与链",
        [
            "LCEL(LangChain Expression Language)、管道符 | 、Runnable 接口",
            "OutputParser(StrOutputParser / JsonOutputParser / PydanticOutputParser)",
            "RunnablePassthrough、RunnableParallel、分支与路由",
        ],
        ["构建「翻译 → 润色 → 摘要」三级链"],
        ["为链添加中间步骤日志"],
        "三级处理链",
        ["LCEL", "OutputParser", "Runnable"],
        "承接 Day 25，链式编排是 RAG 流水线的基础。",
    ),
    27: (
        "Memory 记忆机制",
        [
            "对话记忆原理、ChatMessageHistory、RunnableWithMessageHistory",
            "窗口记忆、摘要记忆、基于数据库的持久化记忆",
        ],
        ["给聊天应用加上多会话记忆管理(session_id 隔离)"],
        ["对比窗口记忆 vs 摘要记忆的效果"],
        "多会话记忆管理",
        ["Memory", "session_id", "持久化记忆"],
        "承接 Day 14 多轮对话，为 Day 36 企业知识库会话管理做准备。",
    ),
    28: (
        "文档加载与分割（RAG 第一步）",
        [
            "Document Loaders: PDF、Word、Markdown、网页、CSV 加载实战",
            "文本分割策略: CharacterTextSplitter、RecursiveCharacterTextSplitter",
            "chunk_size 与 chunk_overlap 调优实验、按语义/标题分割",
        ],
        ["把一本 PDF 电子书清洗并分割成高质量文本块"],
        ["对比不同 chunk_size 的分块效果"],
        "PDF 文档分割实战",
        ["Document Loader", "TextSplitter", "chunk 调优"],
        "承接 Day 11 文件操作，RAG 链路第一步。",
    ),
    29: (
        "向量数据库",
        [
            "向量数据库原理(ANN 检索、HNSW 索引通俗讲解)",
            "Chroma 快速上手：入库、检索、元数据过滤",
            "Milvus / FAISS / Pinecone 对比与选型；Retriever 接口",
        ],
        ["构建自己的知识库并做相似度检索测试"],
        ["测试不同 top_k 值对召回的影响"],
        "Chroma 知识库检索",
        ["向量数据库", "Chroma", "Retriever"],
        "承接 Day 20 Embedding，为 Day 30 完整 RAG 做准备。",
    ),
    30: (
        "完整 RAG 系统搭建（核心日！）",
        [
            "RAG 完整链路: 加载 → 分割 → 向量化 → 存储 → 检索 → 增强生成",
            "RAG Prompt 模板设计、引用来源标注、'我不知道'的兜底处理",
        ],
        ["搭建一个完整的企业知识库问答系统（命令行版）"],
        ["测试 10 个问题并记录回答质量"],
        "企业知识库问答系统（命令行版）",
        ["RAG 全链路", "引用溯源", "兜底策略"],
        "RAG 核心日。能力将扩展到 Day 32-37 进阶项目。",
    ),
    31: (
        "周测 + RAG 效果调优实验日",
        [
            "周测",
        ],
        ["检索效果不好怎么办？调 chunk 大小、调 top_k、换 Embedding 模型的对比实验"],
        ["撰写 RAG 调优实验报告"],
        "RAG 调优对比实验",
        ["RAG 调优", "chunk", "top_k", "Embedding"],
        "承接 Day 30，为 Day 32-33 高级 RAG 技术铺垫。",
    ),
    32: (
        "高级 RAG 技术（上）",
        [
            "查询改写(Query Rewriting)、多路查询(Multi-Query)",
            "HyDE(假设性文档嵌入)、上下文压缩",
        ],
        ["对比基础 RAG 与查询改写后的召回率差异"],
        ["实现 Multi-Query 并记录延迟变化"],
        "查询改写增强 RAG",
        ["Query Rewriting", "HyDE", "Multi-Query"],
        "承接 Day 30-31 基础 RAG，提升召回质量。",
    ),
    33: (
        "高级 RAG 技术（下）",
        [
            "混合检索(BM25 + 向量检索)、RRF 融合排序",
            "Rerank 重排序模型(bge-reranker 实战)、父文档检索器",
        ],
        ["构建「混合检索 + 重排」的增强 RAG 流水线"],
        ["对比纯向量 vs 混合检索的 Hit@5"],
        "混合检索 + Rerank 流水线",
        ["BM25", "RRF", "Rerank"],
        "承接 Day 32，为 Day 36-37 企业级项目提供核心技术。",
    ),
    34: (
        "RAG 评估",
        [
            "评估指标: 忠实度、答案相关性、上下文精确率/召回率",
            "Ragas 评估框架实战、构建测试集",
        ],
        ["给自己的 RAG 系统出具评估报告并针对性优化"],
        ["构建 20 条标准问答测试集"],
        "RAG 评估报告",
        ["Ragas", "忠实度", "召回率"],
        "承接 Day 30-33，为项目答辩提供量化依据。",
    ),
    35: (
        "LlamaIndex 框架",
        [
            "LlamaIndex 核心概念、与 LangChain 的对比与选型",
            "用 LlamaIndex 快速重建知识库问答",
        ],
        ["两个框架各自实现同一需求，写对比笔记"],
        ["整理 LangChain vs LlamaIndex 选型决策树"],
        "双框架对比实现",
        ["LlamaIndex", "框架选型"],
        "承接 Day 25-34 LangChain RAG，拓宽技术视野。",
    ),
    36: (
        "阶段项目二（上）—— 企业级知识库问答系统",
        [
            "需求分析、架构设计",
            "文档处理与知识库构建",
            "后端 API 开发",
        ],
        ["多格式文档上传接口", "混合检索 + Rerank 接入"],
        ["绘制系统架构图"],
        "企业知识库后端",
        ["架构设计", "文档上传", "混合检索"],
        "第三阶段核心项目第一天。整合 Day 28-35 全部 RAG 能力。",
    ),
    37: (
        "阶段项目二（下）—— 企业级知识库问答系统",
        [
            "前端界面开发",
            "多轮对话支持、引用溯源展示、流式输出",
        ],
        ["联调测试、Bug 修复"],
        ["录制项目演示视频"],
        "企业知识库全栈系统",
        ["前端", "引用溯源", "流式输出", "会话管理"],
        "项目二收官。能力衔接 Day 39 Agent 开发。",
    ),
    38: (
        "项目答辩与代码评审",
        [
            "每人 10 分钟项目演示与答辩",
            "讲师逐一代码评审、优秀代码分享、重构建议",
        ],
        ["根据评审意见优化项目"],
        ["整理项目 README 与技术博客"],
        "项目二答辩",
        ["答辩", "代码评审", "重构"],
        "第三阶段收官。进入第四阶段 Agent 智能体开发。",
    ),
    39: (
        "Agent 概念与 ReAct 范式",
        [
            "什么是 Agent: 感知-思考-行动循环、与 Chain 的本质区别",
            "ReAct 论文精讲(Thought → Action → Observation)",
        ],
        ["纯手写一个极简 ReAct Agent(理解底层原理)"],
        ["完成「搜索 + 计算」组合任务"],
        "手写 ReAct Agent",
        ["Agent", "ReAct", "Thought-Action-Observation"],
        "第四阶段起点。承接 Day 19 Function Calling。",
    ),
    40: (
        "LangChain Agent 与工具",
        [
            "Tool 的定义(@tool 装饰器)、内置工具生态",
            "create_tool_calling_agent、AgentExecutor、中间步骤观察",
        ],
        ["构建带搜索(Tavily)、代码执行、文件读写能力的 Agent"],
        ["记录 Agent 中间步骤并分析失败案例"],
        "多工具 LangChain Agent",
        ["@tool", "AgentExecutor", "Tavily"],
        "承接 Day 39 ReAct，框架化 Agent 开发。",
    ),
    41: (
        "LangGraph 入门（重点！）",
        [
            "为什么需要 LangGraph: 状态机、图结构编排",
            "State、Node、Edge、条件边、循环",
        ],
        ["用 LangGraph 重写 ReAct Agent、可视化图结构"],
        ["构建一个带人工审批节点的工作流"],
        "LangGraph ReAct + 人工审批",
        ["LangGraph", "State", "Node", "Edge"],
        "承接 Day 40，图编排是 Day 48-49 多 Agent 项目核心。",
    ),
    42: (
        "LangGraph 进阶",
        [
            "持久化(Checkpointer)、中断与恢复(Human-in-the-loop)",
            "子图、并行节点、错误重试策略",
        ],
        ["构建「写作 Agent」: 大纲 → 分章节并行写作 → 汇总润色"],
        ["测试中断恢复流程"],
        "写作 Agent 工作流",
        ["Checkpointer", "并行节点", "重试策略"],
        "承接 Day 41，为项目三的中断恢复能力做准备。",
    ),
    43: (
        "多 Agent 系统",
        [
            "多 Agent 架构模式: Supervisor 模式、协作模式、层级模式",
            "LangGraph 实现 Supervisor 多 Agent 系统",
        ],
        ["构建「研究团队」: 搜索员 + 分析师 + 报告撰写员协作"],
        ["绘制多 Agent 协作时序图"],
        "研究团队多 Agent",
        ["Supervisor", "多 Agent 协作"],
        "承接 Day 41-42，为 Day 48-49 项目三提供架构模式。",
    ),
    44: (
        "MCP 与 Agent 生态",
        [
            "MCP(Model Context Protocol)协议详解、MCP Server 开发",
            "接入现成 MCP 服务、Agent 记忆系统设计(短期/长期记忆)",
        ],
        ["开发一个自己的 MCP Server 并接入 Agent"],
        ["阅读 MCP 协议规范文档"],
        "自定义 MCP Server",
        ["MCP", "Agent 记忆"],
        "承接 Day 43 多 Agent，拓展 Agent 生态能力。",
    ),
    45: (
        "周测 + Dify / Coze 低代码平台",
        [
            "周测",
        ],
        ["Dify 平台实战: 可视化编排工作流、知识库、发布应用"],
        ["讨论: 低代码平台 vs 代码开发的适用边界"],
        "Dify 工作流实战",
        ["Dify", "低代码", "工作流"],
        "第四阶段中期。对比代码开发与低代码平台。",
    ),
    46: (
        "Agent 稳定性与工程化",
        [
            "Agent 常见失败模式与调试技巧、LangSmith 追踪调试",
            "输出校验、护栏(Guardrails)、成本与延迟优化",
        ],
        ["给 Agent 加上完整的可观测性与容错"],
        ["分析 5 个 Agent 失败案例并修复"],
        "Agent 可观测性改造",
        ["LangSmith", "Guardrails", "容错"],
        "承接 Day 40-44，提升 Agent 生产可用性。",
    ),
    47: (
        "实用 Agent 场景专题",
        [
            "Text-to-SQL 数据分析 Agent(连接真实数据库查询)",
            "浏览器自动化 Agent 概念、代码助手 Agent",
        ],
        ["构建「用自然语言查销售数据」的 SQL Agent"],
        ["测试 10 个自然语言查询"],
        "SQL Agent",
        ["Text-to-SQL", "数据分析 Agent"],
        "承接 Day 46 工程化，为项目三提供场景参考。",
    ),
    48: (
        "阶段项目三（上）—— 多 Agent 智能办公助手",
        [
            "架构设计、Agent 角色划分",
            "工具开发(日程/邮件草拟/网络搜索/文档 RAG)",
        ],
        ["LangGraph 编排初版"],
        ["评审架构方案"],
        "多 Agent 办公助手架构",
        ["架构设计", "工具开发", "角色划分"],
        "第四阶段核心项目。整合 Day 39-47 全部 Agent 能力。",
    ),
    49: (
        "阶段项目三（下）—— 多 Agent 智能办公助手",
        [
            "LangGraph 编排完善",
            "人工确认环节、前端界面、联调",
        ],
        ["功能验收: 3+ Agent、5+ 工具、中断恢复"],
        ["录制演示视频"],
        "多 Agent 办公助手全栈",
        ["LangGraph", "Human-in-the-loop", "前端"],
        "项目三收官。衔接第五阶段微调与部署。",
    ),
    50: (
        "项目答辩 + 阶段复盘",
        [
            "项目三答辩",
            "阶段复盘、知识图谱串讲",
        ],
        ["优化代码并整理文档"],
        ["准备微调阶段预习材料"],
        "项目三答辩",
        ["答辩", "复盘"],
        "第四阶段收官。进入模型微调与部署。",
    ),
    51: (
        "模型微调理论",
        [
            "什么时候需要微调 vs RAG vs Prompt(决策树)",
            "全量微调、LoRA、QLoRA 原理通俗讲解",
            "GPU 基础知识、显存估算、AutoDL/魔搭等算力平台租用实操",
        ],
        ["租一台 GPU 服务器并配好环境"],
        ["绘制微调 vs RAG vs Prompt 决策树"],
        "GPU 环境搭建",
        ["微调理论", "LoRA", "GPU 算力"],
        "第五阶段起点。承接前四阶段全部能力。",
    ),
    52: (
        "数据集构建",
        [
            "指令微调数据格式(Alpaca / ShareGPT 格式)",
            "数据清洗、去重、用大模型辅助生成训练数据(Self-Instruct)",
        ],
        ["构建一个 500 条的垂直领域(如客服)微调数据集"],
        ["检查数据质量：重复率、格式合规率"],
        "客服微调数据集",
        ["Alpaca 格式", "Self-Instruct", "数据清洗"],
        "承接 Day 51，为 Day 53 LLaMA-Factory 训练准备数据。",
    ),
    53: (
        "LLaMA-Factory 微调实战",
        [
            "LLaMA-Factory 安装与配置、WebUI 使用",
            "对 Qwen2.5-7B 做 LoRA 微调、训练参数详解(学习率/epoch/batch size)",
        ],
        ["跑通完整微调流程，观察 loss 曲线"],
        ["记录训练参数与 loss 变化"],
        "Qwen2.5 LoRA 微调",
        ["LLaMA-Factory", "LoRA", "训练参数"],
        "承接 Day 52 数据集，完成首次微调训练。",
    ),
    54: (
        "微调评估与模型合并",
        [
            "微调前后效果对比评估、过拟合识别与处理",
            "LoRA 权重合并、模型量化(GPTQ/AWQ/GGUF 概念)",
        ],
        ["合并模型并量化导出"],
        ["对比微调前后 20 个测试问题"],
        "模型合并与量化",
        ["评估", "过拟合", "量化"],
        "承接 Day 53 训练，为 Day 55 部署做准备。",
    ),
    55: (
        "本地部署与推理服务",
        [
            "Ollama 本地部署模型、OpenAI 兼容接口",
            "vLLM 高性能推理部署、吞吐量压测对比",
        ],
        ["把微调后的模型用 vLLM 部署成 API 服务并接入之前的应用"],
        ["压测对比 Ollama vs vLLM"],
        "vLLM 推理服务",
        ["Ollama", "vLLM", "OpenAI 兼容接口"],
        "承接 Day 54 合并模型，实现本地推理。",
    ),
    56: (
        "应用部署工程化",
        [
            "Docker 入门: 镜像、容器、Dockerfile 编写",
            "Docker Compose 编排(应用 + 向量库 + 数据库)、云服务器部署上线",
        ],
        ["把知识库项目容器化并部署到公网可访问"],
        ["编写 docker-compose.yml 并测试"],
        "Docker 容器化部署",
        ["Docker", "Docker Compose", "云部署"],
        "承接 Day 37 知识库项目，实现生产级部署。",
    ),
    57: (
        "周测 + 安全与合规专题",
        [
            "周测",
        ],
        ["大模型应用安全: 内容审核接入、敏感信息脱敏、备案合规常识、成本监控"],
        ["为项目添加内容审核与脱敏模块"],
        "安全合规改造",
        ["内容审核", "脱敏", "合规"],
        "第五阶段收官。为毕业设计提供部署与安全能力。",
    ),
    58: (
        "毕业设计启动",
        [
            "选题指导(8 个备选方向 + 支持自选)",
            "需求文档撰写、技术方案设计、讲师一对一评审方案",
        ],
        ["确定选题并完成需求文档 v1"],
        ["调研竞品与参考文献"],
        "毕业设计需求文档",
        ["选题", "需求分析", "技术方案"],
        "第六阶段起点。综合运用前 57 天全部技能。",
    ),
    59: (
        "毕业设计开发 Day 1",
        ["项目骨架搭建"],
        ["核心数据/知识库准备"],
        ["每日导师辅导"],
        "项目骨架 + 数据准备",
        ["项目初始化", "数据准备"],
        "毕业设计第 1 天。",
    ),
    60: (
        "毕业设计开发 Day 2",
        ["核心功能开发(RAG / Agent 主链路)"],
        ["核心功能开发(续)"],
        ["导师辅导"],
        "核心功能开发",
        ["RAG/Agent 主链路"],
        "毕业设计第 2 天。",
    ),
    61: (
        "毕业设计开发 Day 3",
        ["核心功能开发(工具、记忆、多轮交互)"],
        ["核心功能开发(续)"],
        ["导师辅导"],
        "工具与记忆模块",
        ["工具", "记忆", "多轮交互"],
        "毕业设计第 3 天。",
    ),
    62: (
        "毕业设计开发 Day 4",
        ["前端界面 + 后端 API 联调"],
        ["联调与 Bug 修复"],
        ["导师辅导"],
        "前后端联调",
        ["前端", "API 联调"],
        "毕业设计第 4 天。",
    ),
    63: (
        "毕业设计开发 Day 5",
        ["测试、评估报告、性能与成本优化"],
        ["优化与测试(续)"],
        ["导师辅导"],
        "测试与优化",
        ["测试", "评估", "性能优化"],
        "毕业设计第 5 天。",
    ),
    64: (
        "毕业设计开发 Day 6",
        ["Docker 部署上线"],
        ["录制演示视频、撰写项目文档"],
        ["导师辅导"],
        "部署与文档",
        ["Docker 部署", "演示视频", "文档"],
        "毕业设计第 6 天。",
    ),
    65: (
        "毕业答辩",
        ["每人 15 分钟演示 + 10 分钟答辩，企业评委参与打分"],
        ["答辩(续)"],
        ["整理答辩反馈"],
        "毕业答辩",
        ["答辩", "演示"],
        "毕业设计答辩日。",
    ),
    66: (
        "简历与作品集打磨",
        [
            "技术简历撰写方法、项目经历 STAR 法则包装",
            "GitHub 仓库整理、README 规范、个人作品集页面",
        ],
        ["完成个人简历 v2", "整理 GitHub 主页"],
        ["请同学互评简历"],
        "简历与作品集",
        ["简历", "STAR", "GitHub"],
        "就业冲刺第一天。",
    ),
    67: (
        "面试专题（一）—— 技术八股",
        [
            "高频面试题精讲: Transformer/注意力机制、RAG 优化、Agent 设计",
            "Python 与工程问题、模拟笔试",
        ],
        ["完成 50 道面试题自测"],
        ["整理错题本"],
        "面试题自测",
        ["面试八股", "Transformer", "RAG", "Agent"],
        "就业冲刺。",
    ),
    68: (
        "面试专题（二）—— 项目深挖与系统设计",
        [
            "如何应对「项目被问穿」、系统设计题(设计一个企业知识库系统)",
            "两两模拟面试 + 讲师点评",
        ],
        ["准备 3 个项目的深挖问答"],
        ["模拟面试复盘"],
        "模拟面试",
        ["项目深挖", "系统设计"],
        "就业冲刺。",
    ),
    69: (
        "模拟面试日",
        ["一对一全真模拟面试(技术面 + HR 面)，逐人反馈改进清单"],
        ["模拟面试(续)"],
        ["根据反馈改进"],
        "全真模拟面试",
        ["模拟面试", "HR 面"],
        "就业冲刺。",
    ),
    70: (
        "结业日",
        [
            "行业前沿分享(多模态 Agent、具身智能趋势)、持续学习路线图",
            "结业典礼、优秀学员分享、就业资源对接",
        ],
        ["课程总结、领取结业证书"],
        ["制定个人 90 天持续学习计划"],
        "结业典礼",
        ["行业前沿", "持续学习"],
        "课程终点。70 天学习旅程圆满收官。",
    ),
}


def get_phase(day: int) -> dict:
    for p in PHASES:
        if p["days"][0] <= day <= p["days"][1]:
            return p
    return PHASES[-1]
